[package]
org= "ballerinax"
name= "microsoft.excel"
version= "1.0.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["microsoft", "excel", "workbook", "worksheet", "sheets"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.excel"
